### ISSUE TITLE
Docker container "mongo-setup" exits after creation

### ISSUE THREAD

**Issue by satvikt** [theopenconversationkit/tock-docker#31]
I have used multiple docker compose files
- docker-compose.yml
- docker-compose-bot.yml

However, the container "mongo-setup" exits after showing the following log:

```
mongo-setup  | Waiting for startup..
mongo-setup  | Started..
mongo-setup  | setup.sh time now: 14:55:47
mongo-setup  | Current Mongosh Log ID:	64d3a8f42b0fb1647e0827ba
mongo-setup  | Connecting to:		mongodb://mongo:27017/?directConnection=true&appName=mongosh+1.6.0
mongo-setup  | Using MongoDB:		6.0.2
mongo-setup  | Using Mongosh:		1.6.0
mongo-setup  | 
mongo-setup  | For mongosh info see: https://docs.mongodb.com/mongodb-shell/
mongo-setup  | 
mongo-setup  | ------
mongo-setup  |    The server generated these startup warnings when booting
mongo-setup  |    2023-08-09T14:55:35.564+00:00: Using the XFS filesystem is strongly recommended with the WiredTiger storage engine. See http://dochub.mongodb.org/core/prodnotes-filesystem
mongo-setup  |    2023-08-09T14:55:36.406+00:00: Access control is not enabled for the database. Read and write access to data and configuration is unrestricted
mongo-setup  |    2023-08-09T14:55:36.406+00:00: You are running in OpenVZ which can cause issues on versions of RHEL older than RHEL6
mongo-setup  |    2023-08-09T14:55:36.406+00:00: vm.max_map_count is too low
mongo-setup  | ------
mongo-setup  | 
mongo-setup  | ------
mongo-setup  |    Enable MongoDB's free cloud-based monitoring service, which will then receive and display
mongo-setup  |    metrics about your deployment (disk utilization, CPU, operation statistics, etc).
mongo-setup  |    
mongo-setup  |    The monitoring data will be available on a MongoDB website with a unique URL accessible to you
mongo-setup  |    and anyone you share the URL with. MongoDB may use this information to make product
mongo-setup  |    improvements and to suggest MongoDB products and deployment options to you.
mongo-setup  |    
mongo-setup  |    To enable free monitoring, run the following command: db.enableFreeMonitoring()
mongo-setup  |    To permanently disable this reminder, run the following command: db.disableFreeMonitoring()
mongo-setup  | ------
mongo-setup  | 
mongo-setup  | test> ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... 
mongo-setup  | test> { ok: 1 }
mongo-setup  | tock [direct: other] test> {
mongo-setup  |   ok: 1,
mongo-setup  |   '$clusterTime': {
mongo-setup  |     clusterTime: Timestamp({ t: 1691592949, i: 1 }),
mongo-setup  |     signature: {
mongo-setup  |       hash: Binary(Buffer.from("0000000000000000000000000000000000000000", "hex"), 0),
mongo-setup  |       keyId: Long("0")
mongo-setup  |     }
mongo-setup  |   },
mongo-setup  |   operationTime: Timestamp({ t: 1691592949, i: 1 })
mongo-setup  | }
```

Also, I am getting the following error traceback for the "admin-api" container, when I run the "admin-web" container

```
tock-docker-admin_web-1  | com.mongodb.MongoWriteException: Write operation error on server mongo:27017. Write error: WriteError{code=66, message='After applying the update, the (immutable) field '_id' was found to have been altered to _id: "64d3a90383f9d0324d2f931a"', details={}}.
tock-docker-admin_web-1  | 	at com.mongodb.client.internal.MongoCollectionImpl.executeSingleWriteRequest(MongoCollectionImpl.java:1032)
tock-docker-admin_web-1  | 	at com.mongodb.client.internal.MongoCollectionImpl.executeReplaceOne(MongoCollectionImpl.java:572)
tock-docker-admin_web-1  | 	at com.mongodb.client.internal.MongoCollectionImpl.replaceOne(MongoCollectionImpl.java:555)
tock-docker-admin_web-1  | 	at org.litote.kmongo.MongoCollectionsKt.replaceOneWithFilter(MongoCollections.kt:404)
tock-docker-admin_web-1  | 	at ai.tock.nlp.front.storage.mongo.EntityTypeDefinitionMongoDAO.save(EntityTypeDefinitionMongoDAO.kt:77)
tock-docker-admin_web-1  | 	at ai.tock.nlp.front.service.ConfigurationRepository.initRepository(ConfigurationRepository.kt:239)
tock-docker-admin_web-1  | 	at ai.tock.nlp.front.service.ApplicationConfigurationService.initializeConfiguration(ApplicationConfigurationService.kt:304)
tock-docker-admin_web-1  | 	at ai.tock.nlp.front.client.FrontClient.initializeConfiguration(FrontClient.kt)
tock-docker-admin_web-1  | 	at ai.tock.nlp.front.ioc.FrontIoc.setup(FrontIoc.kt:69)
tock-docker-admin_web-1  | 	at ai.tock.bot.admin.StartBotAdminServerKt.startAdminServer(startBotAdminServer.kt:30)
tock-docker-admin_web-1  | 	at ai.tock.bot.admin.StartBotAdminServerKt.main(startBotAdminServer.kt:25)
tock-docker-admin_web-1  | 	at ai.tock.bot.admin.StartBotAdminServerKt.main(startBotAdminServer.kt)
tock-docker-admin_web-1  | 2023-08-09 14:56:03,802 WARN  [main] a.t.n.f.s.ConfigurationRepository: Fail to save built-in entity type duckling:temperature
tock-docker-admin_web-1  | com.mongodb.MongoWriteException: Write operation error on server mongo:27017. Write error: WriteError{code=66, message='After applying the update, the (immutable) field '_id' was found to have been altered to _id: "64d3a90383f9d0324d2f931b"', details={}}.
tock-docker-admin_web-1  | 	at com.mongodb.client.internal.MongoCollectionImpl.executeSingleWriteRequest(MongoCollectionImpl.java:1032)
tock-docker-admin_web-1  | 	at com.mongodb.client.internal.MongoCollectionImpl.executeReplaceOne(MongoCollectionImpl.java:572)
tock-docker-admin_web-1  | 	at com.mongodb.client.internal.MongoCollectionImpl.replaceOne(MongoCollectionImpl.java:555)
tock-docker-admin_web-1  | 	at org.litote.kmongo.MongoCollectionsKt.replaceOneWithFilter(MongoCollections.kt:404)
tock-docker-admin_web-1  | 	at ai.tock.nlp.front.storage.mongo.EntityTypeDefinitionMongoDAO.save(EntityTypeDefinitionMongoDAO.kt:77)
tock-docker-admin_web-1  | 	at ai.tock.nlp.front.service.ConfigurationRepository.initRepository(ConfigurationRepository.kt:239)
tock-docker-admin_web-1  | 	at ai.tock.nlp.front.service.ApplicationConfigurationService.initializeConfiguration(ApplicationConfigurationService.kt:304)
tock-docker-admin_web-1  | 	at ai.tock.nlp.front.client.FrontClient.initializeConfiguration(FrontClient.kt)
tock-docker-admin_web-1  | 	at ai.tock.nlp.front.ioc.FrontIoc.setup(FrontIoc.kt:69)
tock-docker-admin_web-1  | 	at ai.tock.bot.admin.StartBotAdminServerKt.startAdminServer(startBotAdminServer.kt:30)
tock-docker-admin_web-1  | 	at ai.tock.bot.admin.StartBotAdminServerKt.main(startBotAdminServer.kt:25)
tock-docker-admin_web-1  | 	at ai.tock.bot.admin.StartBotAdminServerKt.main(startBotAdminServer.kt)
tock-docker-admin_web-1  | 2023-08-09 14:56:03,821 WARN  [main] a.t.n.f.s.ConfigurationRepository: Fail to save built-in entity type duckling:number
tock-docker-admin_web-1  | com.mongodb.MongoWriteException: Write operation error on server mongo:27017. Write error: WriteError{code=66, message='After applying the update, the (immutable) field '_id' was found to have been altered to _id: "64d3a90383f9d0324d2f931c"', details={}}.
tock-docker-admin_web-1  | 	at com.mongodb.client.internal.MongoCollectionImpl.executeSingleWriteRequest(MongoCollectionImpl.java:1032)
tock-docker-admin_web-1  | 	at com.mongodb.client.internal.MongoCollectionImpl.executeReplaceOne(MongoCollectionImpl.java:572)
tock-docker-admin_web-1  | 	at com.mongodb.client.internal.MongoCollectionImpl.replaceOne(MongoCollectionImpl.java:555)
tock-docker-admin_web-1  | 	at org.litote.kmongo.MongoCollectionsKt.replaceOneWithFilter(MongoCollections.kt:404)
tock-docker-admin_web-1  | 	at ai.tock.nlp.front.storage.mongo.EntityTypeDefinitionMongoDAO.save(EntityTypeDefinitionMongoDAO.kt:77)
tock-docker-admin_web-1  | 	at ai.tock.nlp.front.service.ConfigurationRepository.initRepository(ConfigurationRepository.kt:239)
tock-docker-admin_web-1  | 	at ai.tock.nlp.front.service.ApplicationConfigurationService.initializeConfiguration(ApplicationConfigurationService.kt:304)
tock-docker-admin_web-1  | 	at ai.tock.nlp.front.client.FrontClient.initializeConfiguration(FrontClient.kt)
tock-docker-admin_web-1  | 	at ai.tock.nlp.front.ioc.FrontIoc.setup(FrontIoc.kt:69)
tock-docker-admin_web-1  | 	at ai.tock.bot.admin.StartBotAdminServerKt.startAdminServer(startBotAdminServer.kt:30)
tock-docker-admin_web-1  | 	at ai.tock.bot.admin.StartBotAdminServerKt.main(startBotAdminServer.kt:25)
tock-docker-admin_web-1  | 	at ai.tock.bot.admin.StartBotAdminServerKt.main(startBotAdminServer.kt)
tock-docker-admin_web-1  | 2023-08-09 14:56:03,845 WARN  [main] a.t.n.f.s.ConfigurationRepository: Fail to save built-in entity type duckling:distance
tock-docker-admin_web-1  | com.mongodb.MongoWriteException: Write operation error on server mongo:27017. Write error: WriteError{code=66, message='After applying the update, the (immutable) field '_id' was found to have been altered to _id: "64d3a90383f9d0324d2f931e"', details={}}.
tock-docker-admin_web-1  | 	at com.mongodb.client.internal.MongoCollectionImpl.executeSingleWriteRequest(MongoCollectionImpl.java:1032)
tock-docker-admin_web-1  | 	at com.mongodb.client.internal.MongoCollectionImpl.executeReplaceOne(MongoCollectionImpl.java:572)
tock-docker-admin_web-1  | 	at com.mongodb.client.internal.MongoCollectionImpl.replaceOne(MongoCollectionImpl.java:555)
tock-docker-admin_web-1  | 	at org.litote.kmongo.MongoCollectionsKt.replaceOneWithFilter(MongoCollections.kt:404)
tock-docker-admin_web-1  | 	at ai.tock.nlp.front.storage.mongo.EntityTypeDefinitionMongoDAO.save(EntityTypeDefinitionMongoDAO.kt:77)
tock-docker-admin_web-1  | 	at ai.tock.nlp.front.service.ConfigurationRepository.initRepository(ConfigurationRepository.kt:239)
tock-docker-admin_web-1  | 	at ai.tock.nlp.front.service.ApplicationConfigurationService.initializeConfiguration(ApplicationConfigurationService.kt:304)
tock-docker-admin_web-1  | 	at ai.tock.nlp.front.client.FrontClient.initializeConfiguration(FrontClient.kt)
tock-docker-admin_web-1  | 	at ai.tock.nlp.front.ioc.FrontIoc.setup(FrontIoc.kt:69)
tock-docker-admin_web-1  | 	at ai.tock.bot.admin.StartBotAdminServerKt.startAdminServer(startBotAdminServer.kt:30)
tock-docker-admin_web-1  | 	at ai.tock.bot.admin.StartBotAdminServerKt.main(startBotAdminServer.kt:25)
tock-docker-admin_web-1  | 	at ai.tock.bot.admin.StartBotAdminServerKt.main(startBotAdminServer.kt)
tock-docker-admin_web-1  | 2023-08-09 14:56:03,852 WARN  [main] a.t.n.f.s.ConfigurationRepository: Fail to save built-in entity type duckling:volume
tock-docker-admin_web-1  | com.mongodb.MongoWriteException: Write operation error on server mongo:27017. Write error: WriteError{code=66, message='After applying the update, the (immutable) field '_id' was found to have been altered to _id: "64d3a90383f9d0324d2f931f"', details={}}.
tock-docker-admin_web-1  | 	at com.mongodb.client.internal.MongoCollectionImpl.executeSingleWriteRequest(MongoCollectionImpl.java:1032)
tock-docker-admin_web-1  | 	at com.mongodb.client.internal.MongoCollectionImpl.executeReplaceOne(MongoCollectionImpl.java:572)
tock-docker-admin_web-1  | 	at com.mongodb.client.internal.MongoCollectionImpl.replaceOne(MongoCollectionImpl.java:555)
tock-docker-admin_web-1  | 	at org.litote.kmongo.MongoCollectionsKt.replaceOneWithFilter(MongoCollections.kt:404)
tock-docker-admin_web-1  | 	at ai.tock.nlp.front.storage.mongo.EntityTypeDefinitionMongoDAO.save(EntityTypeDefinitionMongoDAO.kt:77)
tock-docker-admin_web-1  | 	at ai.tock.nlp.front.service.ConfigurationRepository.initRepository(ConfigurationRepository.kt:239)
tock-docker-admin_web-1  | 	at ai.tock.nlp.front.service.ApplicationConfigurationService.initializeConfiguration(ApplicationConfigurationService.kt:304)
tock-docker-admin_web-1  | 	at ai.tock.nlp.front.client.FrontClient.initializeConfiguration(FrontClient.kt)
tock-docker-admin_web-1  | 	at ai.tock.nlp.front.ioc.FrontIoc.setup(FrontIoc.kt:69)
tock-docker-admin_web-1  | 	at ai.tock.bot.admin.StartBotAdminServerKt.startAdminServer(startBotAdminServer.kt:30)
tock-docker-admin_web-1  | 	at ai.tock.bot.admin.StartBotAdminServerKt.main(startBotAdminServer.kt:25)
tock-docker-admin_web-1  | 	at ai.tock.bot.admin.StartBotAdminServerKt.main(startBotAdminServer.kt)
tock-docker-admin_web-1  | 2023-08-09 14:56:03,859 WARN  [main] a.t.n.f.s.ConfigurationRepository: Fail to save built-in entity type duckling:amount-of-money
tock-docker-admin_web-1  | com.mongodb.MongoWriteException: Write operation error on server mongo:27017. Write error: WriteError{code=66, message='After applying the update, the (immutable) field '_id' was found to have been altered to _id: "64d3a90383f9d0324d2f9320"', details={}}.
tock-docker-admin_web-1  | 	at com.mongodb.client.internal.MongoCollectionImpl.executeSingleWriteRequest(MongoCollectionImpl.java:1032)
tock-docker-admin_web-1  | 	at com.mongodb.client.internal.MongoCollectionImpl.executeReplaceOne(MongoCollectionImpl.java:572)
tock-docker-admin_web-1  | 	at com.mongodb.client.internal.MongoCollectionImpl.replaceOne(MongoCollectionImpl.java:555)
tock-docker-admin_web-1  | 	at org.litote.kmongo.MongoCollectionsKt.replaceOneWithFilter(MongoCollections.kt:404)
tock-docker-admin_web-1  | 	at ai.tock.nlp.front.storage.mongo.EntityTypeDefinitionMongoDAO.save(EntityTypeDefinitionMongoDAO.kt:77)
tock-docker-admin_web-1  | 	at ai.tock.nlp.front.service.ConfigurationRepository.initRepository(ConfigurationRepository.kt:239)
tock-docker-admin_web-1  | 	at ai.tock.nlp.front.service.ApplicationConfigurationService.initializeConfiguration(ApplicationConfigurationService.kt:304)
tock-docker-admin_web-1  | 	at ai.tock.nlp.front.client.FrontClient.initializeConfiguration(FrontClient.kt)
tock-docker-admin_web-1  | 	at ai.tock.nlp.front.ioc.FrontIoc.setup(FrontIoc.kt:69)
tock-docker-admin_web-1  | 	at ai.tock.bot.admin.StartBotAdminServerKt.startAdminServer(startBotAdminServer.kt:30)
tock-docker-admin_web-1  | 	at ai.tock.bot.admin.StartBotAdminServerKt.main(startBotAdminServer.kt:25)
tock-docker-admin_web-1  | 	at ai.tock.bot.admin.StartBotAdminServerKt.main(startBotAdminServer.kt)
tock-docker-admin_web-1  | 2023-08-09 14:56:03,864 WARN  [main] a.t.n.f.s.ConfigurationRepository: Fail to save built-in entity type duckling:duration
tock-docker-admin_web-1  | com.mongodb.MongoWriteException: Write operation error on server mongo:27017. Write error: WriteError{code=66, message='After applying the update, the (immutable) field '_id' was found to have been altered to _id: "64d3a90383f9d0324d2f9321"', details={}}.
tock-docker-admin_web-1  | 	at com.mongodb.client.internal.MongoCollectionImpl.executeSingleWriteRequest(MongoCollectionImpl.java:1032)
tock-docker-admin_web-1  | 	at com.mongodb.client.internal.MongoCollectionImpl.executeReplaceOne(MongoCollectionImpl.java:572)
tock-docker-admin_web-1  | 	at com.mongodb.client.internal.MongoCollectionImpl.replaceOne(MongoCollectionImpl.java:555)
tock-docker-admin_web-1  | 	at org.litote.kmongo.MongoCollectionsKt.replaceOneWithFilter(MongoCollections.kt:404)
tock-docker-admin_web-1  | 	at ai.tock.nlp.front.storage.mongo.EntityTypeDefinitionMongoDAO.save(EntityTypeDefinitionMongoDAO.kt:77)
tock-docker-admin_web-1  | 	at ai.tock.nlp.front.service.ConfigurationRepository.initRepository(ConfigurationRepository.kt:239)
tock-docker-admin_web-1  | 	at ai.tock.nlp.front.service.ApplicationConfigurationService.initializeConfiguration(ApplicationConfigurationService.kt:304)
tock-docker-admin_web-1  | 	at ai.tock.nlp.front.client.FrontClient.initializeConfiguration(FrontClient.kt)
tock-docker-admin_web-1  | 	at ai.tock.nlp.front.ioc.FrontIoc.setup(FrontIoc.kt:69)
tock-docker-admin_web-1  | 	at ai.tock.bot.admin.StartBotAdminServerKt.startAdminServer(startBotAdminServer.kt:30)
tock-docker-admin_web-1  | 	at ai.tock.bot.admin.StartBotAdminServerKt.main(startBotAdminServer.kt:25)
tock-docker-admin_web-1  | 	at ai.tock.bot.admin.StartBotAdminServerKt.main(startBotAdminServer.kt)
tock-docker-admin_web-1  | 2023-08-09 14:56:03,891 WARN  [main] a.t.n.f.s.ConfigurationRepository: Fail to save built-in entity type duckling:email
tock-docker-admin_web-1  | com.mongodb.MongoWriteException: Write operation error on server mongo:27017. Write error: WriteError{code=66, message='After applying the update, the (immutable) field '_id' was found to have been altered to _id: "64d3a90383f9d0324d2f9322"', details={}}.
tock-docker-admin_web-1  | 	at com.mongodb.client.internal.MongoCollectionImpl.executeSingleWriteRequest(MongoCollectionImpl.java:1032)
tock-docker-admin_web-1  | 	at com.mongodb.client.internal.MongoCollectionImpl.executeReplaceOne(MongoCollectionImpl.java:572)
tock-docker-admin_web-1  | 	at com.mongodb.client.internal.MongoCollectionImpl.replaceOne(MongoCollectionImpl.java:555)
tock-docker-admin_web-1  | 	at org.litote.kmongo.MongoCollectionsKt.replaceOneWithFilter(MongoCollections.kt:404)
tock-docker-admin_web-1  | 	at ai.tock.nlp.front.storage.mongo.EntityTypeDefinitionMongoDAO.save(EntityTypeDefinitionMongoDAO.kt:77)
tock-docker-admin_web-1  | 	at ai.tock.nlp.front.service.ConfigurationRepository.initRepository(ConfigurationRepository.kt:239)
tock-docker-admin_web-1  | 	at ai.tock.nlp.front.service.ApplicationConfigurationService.initializeConfiguration(ApplicationConfigurationService.kt:304)
tock-docker-admin_web-1  | 	at ai.tock.nlp.front.client.FrontClient.initializeConfiguration(FrontClient.kt)
tock-docker-admin_web-1  | 	at ai.tock.nlp.front.ioc.FrontIoc.setup(FrontIoc.kt:69)
tock-docker-admin_web-1  | 	at ai.tock.bot.admin.StartBotAdminServerKt.startAdminServer(startBotAdminServer.kt:30)
tock-docker-admin_web-1  | 	at ai.tock.bot.admin.StartBotAdminServerKt.main(startBotAdminServer.kt:25)
```

Is this due to "mongo-setup" container not running?

**Comment by vsct-jburet** [comment]
Hello,

The mongo setup si just here to enable replicaset. The log is ok and the exit is WAD.

Look at the mongo instance logs - may be there is a problem here
